name: calebh101_server
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.8

dependencies:
  localpkg:
    git:
      url: https://github.com/Calebh101/localpkg-dart.git
      ref: f14b3c7ef9a3af81f999a1c18bb61fb108ea0dc5

  openapi:
    path: ./api_client

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
