name: calebh101_server
description: A Flutter package for my server.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.8
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  openapi:
    path: ./api_client

  args: ^2.7.0
  http: ^1.6.0
  path: ^1.9.1
  yaml: ^3.1.3
  yaml_edit: ^2.2.4
  styled_logger: ^1.0.2
  validators: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

flutter: