name: calebh101_server
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.8

dependencies:
  openapi:
    path: ./api_client

  args: ^2.7.0
  http: ^1.6.0
  path: ^1.9.1
  yaml: ^3.1.3
  yaml_edit: ^2.2.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
